language: node_js
node_js:
  - "5"
install:
  - npm install -g elm@0.17.1
  - npm install -g elm-test
  - elm-package install -y
  - pushd tests && elm-package install -y && popd
script:
  - elm-test
